server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: root
    driveClassName: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        implicitStrategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physicalStrategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl